.travis.yml

This is a start for an automatic regression testing. At least the question "does it build?" can now be answered automatically (and thanks to the integration, also for pullrequests before being merged into the mainline).
This is the foundation for #23 (actual testing)

Integrate with Travis-CI

---

docs/dspdfviewer.1
dspdfviewer.cpp
dspdfviewer.h
pdfviewerwindow.cpp
pdfviewerwindow.h

This will fix #20 - as suggested by @zakkak

New feature: swap secondary screen's function

---

dspdfviewer.cpp
dspdfviewer.h
hyperlinkarea.cpp
pdfrenderfactory.cpp
pdfrenderfactory.h
pdfviewerwindow.cpp
pdfviewerwindow.h
pdfviewerwindow.ui
runtimeconfiguration.cpp
runtimeconfiguration.h
sconnect.h

This is based on the idea from #8 -- The goal being that the bottom pane height is expressed in percent-of-screen, not raw pixels. Especially since screens tend to get physically smaller while logically larger (it's not uncommon to have a Full-HD screen at 15 inch these days).
Don't merge yet.

[WIP] Configurable bottom pane height

---

main.cpp

If main() catches any exception, in addition to spawning a QMessageBox,
it will print those exceptions to stderr.

Duplicate exceptions to the standard error stream

---

pdfviewerwindow.cpp

Fix crash on blanked screen

---

runtimeconfiguration.cpp

In the hope people will read it.

--help: Add pointer to the F1 menu and the manpage

---

.travis.yml
_travis/install_dependencies
hyperlinkarea.cpp
pdfviewerwindow.cpp

This is related to #53 and any feedback on how to verify building works is greatly appreciated.
[Experiments have shown](https://travis-ci.org/dannyedel/dspdfviewer/builds/78134411#L2200) that `brew install poppler --with-qt5` does not work.

Travis: Test OSX too

---

installation/macos.md

they even updated my formula and created a bottle for dspdfviewer. So the latest release does not even need to be compiled for the latest 3 versions of mac os x :smile:

update mac os installation instructions

---

CMakeLists.txt
runtimeconfiguration.cpp
translations/dspdfviewer_de.ts

Finished German translation.
I suggest not to translate the application name. Any translation would sound weird and will only cause confusion - when talking about a certain product, it should be called the same in all languages.

German translation

---

_travis/install_dependencies

Travis [Build 410] errored due to awaiting interactive confirmation to apt-get.
[Build 410]: https://travis-ci.org/dannyedel/dspdfviewer/builds/89046947

travis/deps: Add -y to apt-get install

---

keybindings.ui
pdfviewerwindow.cpp

Fixes #100 
This should make it easier for users to report the version they are running (for bugreports etc)

Add version string to keybindings popup

---

installation/source/options.md

This is the documentation for #105

Document LinkBoostTestDynamic

---

dspdfviewer.cpp
pagepart.cpp
pagepart.h
pdfviewerwindow.cpp
runtimeconfiguration.cpp
runtimeconfiguration.h
testing/CMakeLists.txt
testing/test-thumbnail-cmdline.cc
translations/dspdfviewer_de.ts

This is a part of #103 
Mission:
* Add a RuntimeConfiguration setting to choose thumbnail page part (Left/Both/Right)
* Document it
* Use the configuration value instead of hardcoded values

Make page part used for thumbnails configurable

---

cmake/qrc_embedding.cmake
main.cpp
translations/dspdfviewer_de.ts

Fixes #119 
This PR is complete when:
1. Correct dynamic linking to the system Qt translations (for dynamic linking platforms)
1. Enable static linking to the system Qt translations (if an appropriate CMake option is given)

Embed system qt

---

testing/testhelpers.cc
testing/testhelpers.hh

Missing namespace in testhelpers

---

testing/testhelpers.cc
testing/testhelpers.hh

If this goes through travis without issues, @projekter could you test if this method works in windows/msvc correctly too?

Fix namespace handling

---

.travis.yml
_travis/configure
_travis/test
cmake/compiler_clang.cmake

This PR activates code coverage support for clang

Clang: Activate coverage support

---

.gitignore
CHANGELOG.md
_travis/test
testing/CMakeLists.txt

Add a basic check whether --help and --version contain the version number in their output.

Add test:  Test --help and --version on the command line

---

.travis.yml
installation/windows.md

use a direct link to `/releases/latest` as the recommended installation

Website: installation/windows: Link to "latest release"

---

CHANGELOG.md
cmake/version_number.cmake

Updates changelog for v1.15.
After this gets merged, I will import v1.15 to Debian.

Release v1.15

---

.codecov.yml
.travis.yml

Adjust codecov configuration to the new `yml` file.

Codecov configuration

---

pdfviewerwindow.cpp

Tell Qt that we handled the wheelEvent

---

CHANGELOG.md

prepare changelog for 1.15.1

---

.gitignore
installation/arch.md
installation/daily-deb.md
installation/debian.md
installation/debian/jessie.md
installation/gentoo.md
installation/macos.md
installation/source/options.md
installation/source/stable.md
installation/ubuntu.md
installation/ubuntu/ppa.md
installation/windows.md

Updates documentation to v1.15

Update documentation v1.15
