- docs/dspdfviewer.1
- runtimeconfiguration.cpp
Split from #8
Originally suggested by @mmonaco on 2013-11-16, quoting:
> A config file in the style of OpenVPN or dnsmasq would be nice, they're just fancier ways to specify the long options that are taken on the command line.
This ticket is about the support for a configuration file, that basically takes whatever options the commandline does.
In case of a conflict, order should of course be
command line > configuration file > compile-time default
Most likely, users would configure the helper screen to their liking in the configuration file and mainly use the command line for the `-f` switch (--full-page)
> Configuration file support

- docs/dspdfviewer.1
- pdfviewerwindow.cpp
- pdfviewerwindow.h
> Add message box with keybindings bound to '?' key.

- debug.h
- dspdfviewer.cpp
- hyperlinkarea.cpp
- main.cpp
- pdfdocumentreference.cpp
- pdfrenderfactory.cpp
- pdfviewerwindow.cpp
- renderthread.cpp
- renderutils.cpp
Improve the debugging output throughout, making it more readable and useful.
If I'm compiling with `cmake -DCMAKE_BUILD_TYPE=Debug` I want to see not only *what* is going on, but also where.
Following should be contained in every debug output statement:
* Function name (if known)
* File name (without path)
* Line number
> Improve the debugging output

- main.cpp
- runtimeconfiguration.cpp
- runtimeconfiguration.h
If dspdfviewer is launched without a PDF file on the command line, spawn a Qt File Chooser dialog, allowing the user to pick one from disk.
> Allow file chooser when started without a PDF file parameter

- .travis.yml
- CMakeLists.txt
- debian/rules
Rather than failing the build when it can't determine a version number, the build system should have a fallback (which should probably be something like `vNEXT-rc`, so bug reports built from that build system can be identified).
Any system-specific versionings (like debians changelog) should be parsed in the system-specific build instruction, and the result passed as environment variable or similar. cmake can then check its presense.
Order or precedence (First one that produces a non-empty string wins)
1. `cmake -DDSPDFVIEWER_VERSION=1.2.3.4`
2. If the directory `.git` exists, run `git describe`
3. System specific, given in environment variable
4. fallback version number, in `CMakeLists.txt`.
* Update this on a release tag to the current version number, and immediatly after to "something …
> Rework version number embedding logic

- debian/control
- debian/rules
* Compiling on current sid complains that `hardening-wrapper` is outdated and should be replaced with dpkg-buildflags.
* Right now, the resulting binary will *not* be hardened -- something's off here.
* Drop ubuntu lucid hacks, since lucid is [end of life] and launchpad doesn't build for it anymore anyway.
Goal: No more lintian warnings, while still compiling on wheezy, jessie, sid, and all the currently-supported ubuntus (12.04 and up)
[end of life]: http://www.ubuntu.com/info/release-end-of-life
> Clean up debian/ directory

- debug.h
- main.cpp
Changed application type to Windows GUI so that the console windows does not show up automatically.
Note that this also means that there will never be a console or output to a console window in any case. If you used the console at some point to print a message without at the same time giving a window popup, this message will not be seen.
> Hiding console

- CMakeLists.txt
- docs/dspdfviewer.1
- dspdfviewer.cpp
- pdfviewerwindow.cpp
- pdfviewerwindow.h
- runtimeconfiguration.cpp
- runtimeconfiguration.h
This pull requests adds preliminary support for the i3 window manager via shellcode workaround.
This closes #3.
@adnidor, could you build again from the current commit and confirm it still works correctly? Then I would import this to the mainline, allowing people to test it via command-line-switch.
> New feature: support for the i3 window manager

- .travis.yml
- CMakeLists.txt
- debian/rules
While trying to build a proper debian package #55 I discovered a Fails-To-Build-From-Source Bug in debian sid, but not any other.
Right now, if I explicitely state that I *don't* want the cxx11 ABI, the compile goes through cleanly. However, it is possible that the problem is on the boost side since the error message one gets - see https://travis-ci.org/dannyedel/dspdfviewer/builds/73694510 for a complete build log - seems to suggest that boost's header exports a `program_options` with the new `std::__cxx11::basic_string` as a template parameter, but gcc's linker can't find it.
As soon as a clean-room (`sbuild`) build on `sid` works again, merge this pull request but ***remember to revert the .travis.yml*** to the "just use the current ubuntu environment to build quickly" mode for …
> Revert _USE_CXX11_ABI related changes

- CMakeLists.txt
- poppler-qt.h
This should™ be more stable than find_library, especially because it *also* lists the include directories.
This, in turn, allows to simply `#include <poppler-qtX.h>`, avoiding the prefixes, which makes it even nicer.
> CMakeLists: use pkg-config to find poppler

- _travis/install_dependencies
- debian/control
- debian/copyright
Since db1955e3ac00a29461b24d7f59a5ea6be0d82f59 CMakeList uses CMake's pkg-config module to find poppler includes and libraries.
pkg-config was not added to d/control, but since pkg-config was installed on travis, that error got unnoticed.
> Debian: Add pkgconfig to dependencies

- CMakeLists.txt
- adjustedlink.cpp
- debug.h
- dspdfviewer.cpp
- dspdfviewer.h
- hyperlinkarea.cpp
- pdfdocumentreference.h
- pdfpagereference.cpp
- pdfrenderfactory.cpp
- pdfviewerwindow.cpp
- pdfviewerwindow.h
- renderingidentifier.cpp
- renderingidentifier.h
- renderthread.cpp
- renderutils.cpp
Compiling with clangs `-Weverything` exposed a lot more little things that may one day become a problem.
Mostly this is unmarked signed<->unsigned operations or float<->int, but clang also warns about shadowing (using a function parameter that hides an object property).
Generally use boost's numeric_cast for signed<->unsigned conversions (this will range check) and use boost's iround for float->int rounding.
> Fix Clang warnings in the source code

- .travis.yml
- CMakeLists.txt
- _travis/install_dependencies
- pdfviewerwindow.cpp
Depend on Qt >= 5.1.1 because of QT Bug 32100:
https://bugreports.qt.io/browse/QTBUG-32100
This bug is the actual reason for the compilation failing on Qt5+clang. This is not a problem on Debian (stable and wheezy-backports both have 5.3.2), but it is on Ubuntu precise, where travis' containers run on.
So fixing this means backporting qtbase onto precise.
> Qt5: Depend on version 5.1.1

- CMakeLists.txt
- keybindings.ui
- pdfviewerwindow.cpp
- translations/dspdfviewer_de.ts
Currently it's a HTML-formatted label. While there's nothing wrong with that, it will probably confuse translators after #40 is merged (not every translator will type correctly formatted html).
If its refactored into its own .ui file, it will have its own class which should provide enough context to translators.
> Refactor the Help Dialog box into its own .ui file

- pdfviewerwindow.cpp
This fixes the display of the presentation clock.
> pdfviewerwindow: change tr() to translate()

- CMakeLists.txt
- pdfviewerwindow.cpp
Fix of last pull request #84 (detection of MSVC - there seems to be a difference between CMAKE_CXX_COMPILER_ID and "${CMAKE_CXX_COMPILER_ID}").
Fixed #87.
> Display window on startup

- pdfviewerwindow.cpp
Fixes #90.
@projekter, could you verify that under Windows, this branch compiles and works as intended (Windows spawning on correct screens)?  Since it does not work anymore under my Linux box, I've added `&& defined(_WIN32)` to the code, but I can't check if it works.
> Use QWindow and setScreen only on WIN32

- .travis.yml
This should avoid the problem of pull-requests getting build twice (once
as push, and once as pull-request)
> travis: only build master branch

- .travis.yml
Last month, travis-ci announced[1] trusty beta, adding a "dist" keyword
to select a trusty machine.
[1]: http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/
> Travis: correctly specify trusty beta

- CMakeLists.txt
- _travis/install_dependencies
- cmake/compiler_clang.cmake
- cmake/qrc_embedding.cmake
- dspdfviewer.qrc
- main.cpp
- testing/CMakeLists.txt
This loads the translation file from the Qt Resource system by copying
the qrc file into the build tree, and then running rcc (which would
otherwise search for the qm files in the source tree)
Fixes #77.
> Load translation from resources

- .travis.yml
This should fix double execution of travis on PRs, like in #106
> travis.yml: Only build gh-pages and pull requests

- .travis.yml
- CMakeLists.txt
- _travis/compile
- _travis/test
- cmake/external_libraries.cmake
- testing/testhelpers.hh
Allows one to choose boost link type at `cmake` step. @projekter has shown it makes sense at least on windows, to link statically, because there's no standard package manager system that ensures dynamic libraries are present at run-time.
This is a part of #104
> Make link-type (static/dynamic) of boost a cmake variable

- CMakeLists.txt
Without using any compiler- or OS-specific flags.
> Set library name to libdspdfviewer

- testing/CMakeLists.txt
In case those are not installed, the "is the correct language set" checks will fail at the `ctest` step.
With this patch, they will fail at the `cmake` step with an appropriate error message.
> tests: Check for xvfb-run and env at CMake step

- testing/testhelpers.hh
These are clearly not system headers, so they should use the local include syntax.
Also, using the system header include style called build failures on certain compilers.
> testhelpers.hh: Use relative path for headers

- CMakeLists.txt
- cmake/external_libraries.cmake
- cmake/platforms.cmake
- testing/CMakeLists.txt
Add minimal support for the MSYS2/MinGW environment.
* Add a new CMake variable `WINDOWS` that gets activated on MSVC and MinGW
* Disable locale-switching unittests if `WINDOWS` (Switching locale works differently there)
* Throw error at cmake step if `pdflatex` is not found, but `DownloadTestPDF` is `OFF`.
> Add MinGW support

- testing/CMakeLists.txt
Windows by default doesn't have an `env` program, so don't fail cmake on Windows if it is not present.
> Search for env only on non-windows platform

- .gitignore
- cmake/external_libraries.cmake
- docs/Windows/license.html
- pagepart.cpp
- pdfviewerwindow.cpp
Inclusion of Windows dependencies with absolute paths, first fix for #104.
Fixes a compile failure in c46de22266b43f253c4cb81c2636e7e5d83f8d3b.
Closes #99.
> Windows dependencies

- cmake/external_libraries.cmake
- pdfviewerwindow.cpp
Currently the list of statically linked `.lib` files gets activated if `WINDOWS` is defined.
However, `.lib` files are specific to the MSVC compiler, so compiling fails on MinGW. This PR sets the conditional to `if (MSVC)` and fixes a little build failure with MinGW.
> Fix linking to poppler on MinGW

- cmake/compiler_msvc.cmake
Sorry for this, but you were right in #122. For some reason, it always compiled without this include_directories or it was lost in one of the most recent commits (which I cannot remember). But it is definitely needed.
> Fixed inclusion of directories in MSVC

- CHANGELOG.md
- cmake/version_number.cmake
The number of changes (especially the Qt5 and Windows ports) justify releasing a new version.
I tested building on Debian myself, and I know from @projekter's #122 that it works on Windows.
@wwwdata can you verify this PR builds correctly on OSX? If I get your okay I'll release tomorrow.
* Please note there is now a testsuite, and if you don't specify `-DDownloadTestPDF=ON` on the cmake command line, you need a working latex-beamer installation at build time.
* If you want to build against Qt5, specify `-DUseQtFive=ON` at cmake time.
> Release v1.14

- debian/control
This should™ allow the jenkins daily builds to work correctly again (as in, execute the test suites)
> d/control: Add xvfb dependency

- debian/control
This is also needed for the jenkins debian test system. #127 was incomplete.
> Add xauth dependency

- testing/test-images.cc
- testing/testhelpers.hh
- testing/testrenderonepage.cc
This improves the failed unit test output by providing colors as `#aabbcc` instead of a decimal number.
> boost-test: print colors as hex values

- _travis/compile
- _travis/install_dependencies
- testing/testrenderonepage.cc
This allows for the note page from `colored-rectangles.pdf` to be rendered `0xffffff` (white), which happens on minimally older latex-beamer installations (they ignore note page background color)
Since this is not a dspdfviewer issue, allow the test suite to pass in this case, with a warning.
also update travis to build the PDF during the test run (this should work on precise and trusty now)
> testsuite: Allow white note page

- debug.h
- docs/dspdfviewer.1
- dspdfviewer.cpp
- main.cpp
- pdfdocumentreference.cpp
- pdfdocumentreference.h
- pdfpagereference.h
- pdfrenderfactory.cpp
- pdfrenderfactory.h
- pdfviewerwindow.cpp
- renderingidentifier.cpp
- renderingidentifier.h
- renderthread.cpp
- renderthread.h
- renderutils.cpp
- renderutils.h
- runtimeconfiguration.cpp
- runtimeconfiguration.h
- testing/CMakeLists.txt
- testing/pdfs/many-many-pages.tex
This should fix #140 - not only on windows.
* This PR adds a command line switch `--cache-size`, which is enforced by QCache.
* While the current memory usage estimate is rather dumb (`32bit * width * height`) it does serve to prevent limitless growth.
* This avoids creating one `Poppler::Document` per thread, instead adding a `mutex` to a creation section and let the threads share a `QSharedPointer<Poppler::Document const>`.
* Also adds a WARNINGOUT macro, similar to DEBUGOUT.
* If there are `RenderThreads` still waiting to start and the application is shut down, they will now fail their rendering instantly. (The user won't see it anyway...)
> Improve memory handling

- cmake/external_libraries.cmake
- cmake/filelists.cmake
- qttools is required for LinguistTools
- Xml is one of the additional dependencies that can be found automatically
- Qt does not provide cmake files for PlatformSupport, harfbuzzng, pcre and windows, so I hardcoded them
With those dependencies, this branch succeeds compilation and execution.
> Add dependencies so that static compilation works.

- cmake/compiler_gnu_gcc.cmake
This completely replaces the version-number-based detection for c++11
support, and simply tries the command line switches "-std=c++11" and
"-std=c++0x" in order.
fixes #151
> Compiler/GNU-GCC: Test for c++11 flag, not version

- pdfviewerwindow.cpp
This should fix the problem that sometimes™ (depending on execution
speed -- race condition) a window would stay on its screen and/or end up
un-fullscreened on the correct screen.
This change does not affect Windows, because it's in the `#else` path, but it does affect OSX.
@wwwdata, can you check whether this correctly shows the window on the second screen in OSX when building (a) with qt4 / (b) with qt5?
If it works in qt4, but not qt5, please try whether the win32-style screen setting works.
> Change ordering of "Move to top left" and "Show fullscreen" commands

- CMakeLists.txt
- cmake/external_libraries.cmake
I will drop Qt4 support in v1.16.
So make the default Qt mode Qt5, and use v1.15 to make sure it works as intended on all supported platforms.
> Make Qt5 the default, deprecate qt4

- debian/control
- debian/rules
These are the d/rules and d/control from the official Debian packaging.
> Fake debian/ folder: Update to qt5 build-dependencies

- .appveyor.yml
This PR adds the copy command necessary to load the .dll into the compiled program's folder.
Also adds some minor cleanups to the appveyor.yml file, dropping RDP and try to use MSBuild whenever possible.
fixes #154
> appveyor.yml: Build and test a Debug configuration aswell

- .gitignore
- _config.yml
- installation/windows.md
@projekter: I updated the installation/windows documentation with build-from-source instructions using your Dependency package.
Does this look okay to you?
Edit: Direct link to rendered source: https://github.com/dannyedel/dspdfviewer/blob/add-windows-build-from-source/installation/windows.md
> Docs: Add instructions for windows build from source

- .appveyor.yml
- cmake/compilers.cmake
Checkout CMAKE_BUILD_TYPE does not work with multi-configuration
generators, such as the MSBuild generator used on windows.
> Correctly set -DQT_NO_DEBUG_OUTPUT

- CMakeLists.txt
- _travis/test
- testing/CMakeLists.txt
Use a default testing timeout, instead of error-prone per-test timeouts.
This is mainly useful for windows, where a missing DLL will spawn a warning window that needs to be clicked away.
> Set timeouts on unit tests

- CMakeLists.txt
This is a workaround for #156 -- in part, to check whether the program is actually failing (expect tickets then) or if this is a false-positive situation.
I do not have access to a real big-endian machine to figure out what exactly is going on.  Until someone™ can donate time or a real BE machine to help debug this, disable the testsuite.
Keep #156 open until this is resolved.
> Disable testsuite on big-endian systems

- .travis.yml
Make sure the correct codecov binary gets called, and that it uses llvm-cov when appropriate.
* OSX: Give the correct path to the user library
* Linux/Clang: Use llvm-cov instead of gcov
* Linux/GCC: Call ~/.local/bin/codecov directly
> Travis/Codecov: Fix integration

- .appveyor.yml
This should™ only use Windows functions that are also available on Windows XP.
If nothing else, this allows me to run dspdfviewer under [ReactOS][1] and WinXP VM's which need *a lot* less system resources than Win7 or higher.  So far, I have not seen any indicator that something would not work.
This has no effect on *compiling* dspdfviewer, since MSVC2013 won't run on XP.
[1]: https://reactos.org/
> AppVeyor/MSVC: Use Windows XP toolset

- .travis.yml
- _travis/configure
In #174 it was discovered there are problems when compiling Qt5 on OS X.  Use travis to verify *building* against Qt5 works.
> travis: also build against Qt5 on OSX

- .gitignore
- .travis.yml
- cmake/compiler_clang.cmake
Maybe™ the problem in #174 was because of the more recent compiler version.  Make travis use the `xcode7.3` image in order to test this.
> Travis/OSX: Use latest XCode
